### ISSUE TITLE
VERSION_REGEX does not match ksp version 1.2

### ISSUE THREAD

**Issue by daharp** [Voidi/proprietary_installer#4]
When running the installer script, it downloads version 1.1.3 from the ksp download page. But the latest version (on the date this was written) is 1.2

**Comment by Voidi** [comment]
Sorry for the late answer, this must somewhat slipped my attention.
On my machine it works, (at the time of writing). there may be problems with the SSL certificates of kerbalspaceprogram.com but this would block the download in total and would not get the wrong version.
If you are still interessested in a solution i would need more details (like the output of the commandline)
