### ISSUE TITLE
Request: make a version without download

### ISSUE THREAD

**Issue by 7ranceaddic7** [Voidi/proprietary_installer#5]
Hi, I've been watching this for a while and noticed you on.  

I'm fairly new to *nix; so, could you prune the download code?

I've got KSP1.3 already installed.

**Comment by Voidi** [comment]
My script is still used? :-) I haven't played KSP (and so used my installer) for uhm years, so i don't know if everything work fine (especially the download part).

Please explain what you exactly want:
Have you already downloaded the game as archive from the website, and want the installer do the rest?
or have you extracted the archive in a directory and want only the script to generate a proper launcher/start menu entry?
Both should work in theory.

**Comment by 7ranceaddic7** [comment]
I do the install myself; it's already installed (and heavily modded). 

I notice that it creates a launcher button and wanted that part. So I could add this to my "Favorites" bar.

**Comment by Voidi** [comment]
then simply this command should work
`./ksp_installer "PathToYourInstall"`
for example i installed my ksp to /home/tobias/opt/KSP
so i would run the following command:
`./ksp_installer /home/tobias/opt/KSP`

**Comment by 7ranceaddic7** [comment]
Okay, Linux hates me.

scott@Jupiter:~/Git/MyKSPMods/UI$ ./ksp_installer /home/scott/Games/KSP_1.3
bash: ./ksp_installer: No such file or directory

**Comment by Voidi** [comment]
if a command starts with `./` this would execute a program/scriptfile with this name -if it exist- in the current working directory.
So you have to place the installer script in `~/Git/MyKSPMods/UI` to make the above command call working.

**Comment by 7ranceaddic7** [comment]
So, I have no idea what went wrong that last time, but this time it worked like a charm!!!

Thank you for feeding my inner KSP monster.

scott@Jupiter:~$ cd ~/Git/MyKSPMods/UI
scott@Jupiter:~/Git/MyKSPMods/UI$ ls
ksp_installer.sh  Viewmatic Survey Satellite.png
scott@Jupiter:~/Git/MyKSPMods/UI$ ./ksp_installer.sh ~/Games/KSP_1.3
This seems to be not a vanilla KSP executable
Kerbal Space Program installation in '/home/scott/Games/KSP_1.3' finished. 
scott@Jupiter:~/Git/MyKSPMods/UI$
