### ISSUE TITLE
Process continually runs.

### ISSUE THREAD

**Issue by 7ranceaddic7** [Voidi/proprietary_installer#7]
If you set the exebit and double-click the file the sh process continues to run repeatedly.  I let this run for 10m before pskill.

**Comment by Voidi** [comment]
I Assume your talking about the ksp installer. If you haven't downloaded the ksp archive manual, you must run the script in terminal.

**Comment by 7ranceaddic7** [comment]
Yes.  What is this KSP Archive you speak of?

**Comment by 7ranceaddic7** [comment]
Yeah.  NO worries; that's good enough for me.
